name: Build a package and deploy to Lonti Console

on: [push]

jobs:
  deploy_single_package:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Deploy Martini package to Lonti Console
        uses: lontiplatform/martini-build-pipeline-lonti-managed-hosting@v1
        with:
          instance_name: toro292.et.martiniserver.com
          access_token: ${{ secrets.ACCESS_TOKEN }}
